// <auto-generated />
using System;
using CTTSite.EFDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CTTSite.Migrations
{
    [DbContext(typeof(ItemDbContext))]
    [Migration("20230512070535_CartItem_orderv1")]
    partial class CartItem_orderv1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CTTSite.DAO.CartItem_Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartItemID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CartItem_Orders");
                });

            modelBuilder.Entity("CTTSite.Models.CartItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ItemID");

                    b.HasIndex("UserID");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("CTTSite.Models.Consultation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BookedEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookedNamed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("TelefonNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("CTTSite.Models.Forms.FormActivityDiary", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Day1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_0600")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_0700")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_0800")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_0900")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_1000")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_1100")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_1200")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_1300")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_1400")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_1500")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_1600")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_1700")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_1800")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_1900")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_2000")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_2100")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_2200")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_2300")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_2400")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_0600")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_0700")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_0800")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_0900")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_1000")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_1100")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_1200")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_1300")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_1400")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_1500")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_1600")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_1700")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_1800")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_1900")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_2000")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_2100")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_2200")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_2300")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_2400")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_0600")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_0700")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_0800")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_0900")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_1000")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_1100")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_1200")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_1300")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_1400")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_1500")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_1600")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_1700")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_1800")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_1900")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_2000")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_2100")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_2200")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_2300")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_2400")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_0600")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_0700")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_0800")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_0900")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_1000")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_1100")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_1200")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_1300")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_1400")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_1500")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_1600")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_1700")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_1800")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_1900")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_2000")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_2100")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_2200")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_2300")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_2400")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_0600")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_0700")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_0800")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_0900")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_1000")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_1100")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_1200")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_1300")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_1400")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_1500")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_1600")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_1700")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_1800")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_1900")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_2000")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_2100")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_2200")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_2300")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_2400")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_0600")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_0700")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_0800")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_0900")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_1000")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_1100")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_1200")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_1300")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_1400")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_1500")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_1600")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_1700")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_1800")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_1900")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_2000")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_2100")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_2200")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_2300")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_2400")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_0600")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_0700")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_0800")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_0900")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_1000")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_1100")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_1200")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_1300")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_1400")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_1500")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_1600")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_1700")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_1800")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_1900")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_2000")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_2100")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_2200")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_2300")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_2400")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("FormActivityDiaries");
                });

            modelBuilder.Entity("CTTSite.Models.Forms.FormActivityList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Achievement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exercise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pleasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Social")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("FormActivityLists");
                });

            modelBuilder.Entity("CTTSite.Models.Forms.FormActivitySchedule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Afternoon1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Afternoon2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Afternoon3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Afternoon4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Afternoon5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Afternoon6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Afternoon7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evening1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evening2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evening3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evening4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evening5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evening6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evening7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Morning1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Morning2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Morning3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Morning4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Morning5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Morning6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Morning7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Score1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Score2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Score3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Score4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Score5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Score6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Score7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("FormActivitySchedules");
                });

            modelBuilder.Entity("CTTSite.Models.Forms.FormHotCrossBun", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Behaviours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emotions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Physical")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thoughts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("FormHotCrossBuns");
                });

            modelBuilder.Entity("CTTSite.Models.Forms.FormSleepDiary", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Day1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_AmountOfTimesWokenUp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_HowLongToSleep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_HowRestedDoYouFeel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_TimeGottenOutOfBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_TimeInBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_TimeWokenUpInMorning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_TotalTimeAwakeInNight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_TotalTimeSleeping")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1_TotalTimeSpentInBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_AmountOfTimesWokenUp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_HowLongToSleep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_HowRestedDoYouFeel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_TimeGottenOutOfBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_TimeInBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_TimeWokenUpInMorning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_TotalTimeAwakeInNight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_TotalTimeSleeping")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2_TotalTimeSpentInBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_AmountOfTimesWokenUp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_HowLongToSleep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_HowRestedDoYouFeel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_TimeGottenOutOfBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_TimeInBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_TimeWokenUpInMorning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_TotalTimeAwakeInNight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_TotalTimeSleeping")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day3_TotalTimeSpentInBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_AmountOfTimesWokenUp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_HowLongToSleep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_HowRestedDoYouFeel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_TimeGottenOutOfBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_TimeInBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_TimeWokenUpInMorning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_TotalTimeAwakeInNight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_TotalTimeSleeping")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day4_TotalTimeSpentInBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_AmountOfTimesWokenUp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_HowLongToSleep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_HowRestedDoYouFeel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_TimeGottenOutOfBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_TimeInBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_TimeWokenUpInMorning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_TotalTimeAwakeInNight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_TotalTimeSleeping")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day5_TotalTimeSpentInBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_AmountOfTimesWokenUp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_HowLongToSleep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_HowRestedDoYouFeel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_TimeGottenOutOfBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_TimeInBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_TimeWokenUpInMorning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_TotalTimeAwakeInNight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_TotalTimeSleeping")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day6_TotalTimeSpentInBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_AmountOfTimesWokenUp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_HowLongToSleep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_HowRestedDoYouFeel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_TimeGottenOutOfBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_TimeInBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_TimeWokenUpInMorning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_TotalTimeAwakeInNight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_TotalTimeSleeping")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day7_TotalTimeSpentInBed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("FormSleepDiaries");
                });

            modelBuilder.Entity("CTTSite.Models.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IMG")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("CTTSite.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Cancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("Shipped")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CTTSite.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Staff")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CTTSite.Models.CartItem", b =>
                {
                    b.HasOne("CTTSite.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CTTSite.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
